# Etapa 1: Build
FROM node:20-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Vite crea la carpeta 'dist' por defecto
RUN npm run build 

# Etapa 2: Production
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
# OJO: Aquí copiamos desde /app/dist porque usas Vite
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]